"""Emit the demo seed SQL.

Split from build_demo_seed.py to keep each file readable. Everything here is
string building; the data decisions live in build_demo_seed.
"""

from __future__ import annotations

import math

from build_demo_seed import (
    COMMENTS,
    DIMENSION_LABELS,
    NOTES_GOOD,
    NOTES_MIXED,
    NOTES_POOR,
    RECOMMENDATIONS_PER_USER,
    TEAM_ACCOUNTS,
    Person,
    Place,
    bucket_for,
    choose_visits,
    cosine,
    home_for,
    pick,
    radius_for,
    score_for,
    sql_text,
    stable_int,
)


def recommend_for(
    person: Person,
    places: list[Place],
    visited: dict[str, str],
    scores: dict[str, float],
    friend_scores: dict[str, list[tuple[str, float]]],
    community: dict[str, tuple[int, float]],
    place_by_slug: dict[str, Place],
) -> list[tuple[Place, float, str]]:
    """Score every unvisited place with the Part 8.2 formula.

    Evaluated here rather than by the recommend Edge Function so each account
    ships with a complete, stable recommendation set and the app never needs a
    model call to show a reason.
    """

    category_counts: dict[str, int] = {}
    best_in_category: dict[str, tuple[str, float]] = {}
    for slug in visited:
        place = place_by_slug[slug]
        category_counts[place.category] = category_counts.get(place.category, 0) + 1
        score = scores[slug]
        current = best_in_category.get(place.category)
        if not current or score > current[1]:
            best_in_category[place.category] = (place.name, score)

    top_category = None
    if category_counts:
        top_category = max(category_counts, key=lambda key: category_counts[key])

    scored: list[tuple[Place, float, str]] = []
    for place in places:
        if place.slug in visited:
            continue

        taste_match = max(0.0, min(1.0, cosine(person.taste, place.taste)))

        friends = friend_scores.get(place.slug, [])
        friend_signal = (
            sum(score / 10 for _, score in friends) / len(friends) if friends else 0.35
        )

        count, average = community.get(place.slug, (0, 0.0))
        quality = average / 10 if count >= 3 else place.popularity / 100

        seen = category_counts.get(place.category, 0)
        diversity = 1.0 if seen < 2 else (0.5 if seen < 5 else 0.0)

        crowd_penalty = (1 - person.crowd_tolerance) * (place.crowd_level - 1) * 0.2 / 4
        price_penalty = person.price_sensitivity * place.price_tier * 0.2 / 4

        total = (
            0.45 * taste_match
            + 0.25 * friend_signal
            + 0.15 * quality
            + 0.15 * diversity
            - crowd_penalty
            - price_penalty
        )

        # Part 8.3 reason rules, highest priority first.
        strong = [(name, score) for name, score in friends if score >= 7.5]
        shared = [
            (index, min(person.taste[index], place.taste[index]))
            for index in range(10)
            if min(person.taste[index], place.taste[index]) > 0.65
        ]
        anchor = best_in_category.get(place.category)

        if len(strong) == 1:
            reason = f"{strong[0][0]} rated this {strong[0][1]:.1f}"
        elif len(strong) > 1:
            reason = f"{len(strong)} friends have been here"
        elif shared:
            best = max(shared, key=lambda item: item[1])[0]
            reason = f"You keep rating {DIMENSION_LABELS[best]} spots highly"
        elif anchor:
            reason = f"Because you gave {anchor[0]} a {anchor[1]:.1f}"
        elif seen < 2 and top_category:
            label = top_category.replace("_", " ")
            reason = f"Something different from your usual {label} picks"
        else:
            reason = "Popular with travelers who share your taste"

        scored.append((place, total, reason))

    scored.sort(key=lambda item: (-item[1], item[0].slug))
    return scored[:RECOMMENDATIONS_PER_USER]


def emit(people: list[Person], places: list[Place]) -> str:
    place_by_slug = {place.slug: place for place in places}
    out: list[str] = []
    add = out.append

    add("-- Generated by scripts/build_demo_seed.py. Do not edit by hand.")
    add("--")
    add(f"-- {len(people)} accounts across {len(places)} places, with visits, a")
    add("-- social graph, and a pre-computed recommendation set per account.")
    add("-- Seeded demo accounts sign in with 'journi-demo'.")
    add("")
    add("begin;")
    add("")
    add("delete from auth.users where email like '%@journi.demo';")
    team_emails = ", ".join(sql_text(email) for email in TEAM_ACCOUNTS)
    add(f"delete from auth.users where email in ({team_emails});")
    add("")

    add("insert into auth.users (")
    add("  id, instance_id, aud, role, email, encrypted_password,")
    add("  email_confirmed_at, created_at, updated_at,")
    add("  raw_app_meta_data, raw_user_meta_data,")
    add("  confirmation_token, recovery_token, email_change,")
    add("  email_change_token_new, email_change_token_current,")
    add("  phone_change, phone_change_token, reauthentication_token")
    add(") values")
    rows = [
        f"  ('{person.uid}', '00000000-0000-0000-0000-000000000000',"
        f" 'authenticated', 'authenticated', {sql_text(person.email)},"
        f" extensions.crypt({sql_text(person.password)},"
        f" extensions.gen_salt('bf')),"
        f" now(), now() - interval '400 days', now(),"
        """ '{"provider":"email","providers":["email"]}'::jsonb,"""
        f" jsonb_build_object('full_name', {sql_text(person.display_name)}),"
        " '', '', '', '', '', '', '', '')"
        for person in people
    ]
    add(",\n".join(rows) + ";")
    add("")

    add("insert into auth.identities (")
    add("  provider_id, user_id, identity_data, provider,")
    add("  last_sign_in_at, created_at, updated_at")
    add(") values")
    rows = [
        f"  ('{person.uid}', '{person.uid}',"
        f" jsonb_build_object('sub', '{person.uid}', 'email',"
        f" {sql_text(person.email)}, 'email_verified', true),"
        " 'email', now(), now() - interval '400 days', now())"
        for person in people
    ]
    add(",\n".join(rows) + ";")
    add("")

    add("-- handle_new_user() created a bare profile for each account.")
    for person in people:
        avatar = f"https://i.pravatar.cc/256?u={person.username}"
        home_lat, home_lng, home_label = home_for(person.username, person.home_city)
        vector = "{" + ",".join(str(value) for value in person.taste) + "}"
        add(
            "update public.profiles set "
            f"username = {sql_text(person.username)}, "
            f"display_name = {sql_text(person.display_name)}, "
            f"bio = {sql_text(person.bio)}, "
            f"home_city = {sql_text(home_label)}, "
            f"home_lat = {home_lat}, "
            f"home_lng = {home_lng}, "
            f"home_radius_miles = {radius_for(person.username)}, "
            f"avatar_url = {sql_text(avatar)}, "
            f"is_private = {'true' if person.private else 'false'}, "
            f"taste_vector = '{vector}', "
            f"crowd_tolerance = {person.crowd_tolerance}, "
            f"price_sensitivity = {person.price_sensitivity}, "
            "onboarding_complete = true "
            f"where id = '{person.uid}';"
        )
    add("")

    visited_by: dict[str, dict[str, str]] = {}
    scores_by: dict[str, dict[str, float]] = {}

    add("insert into public.visits (")
    add("  user_id, place_id, bucket, rank_position, score, note, visited_on,")
    add("  was_paid, amount_paid_usd, value_rating, crowd_experienced,")
    add("  time_spent_minutes, companion, would_return, created_at")
    add(") values")
    rows = []
    for person in people:
        chosen = choose_visits(person, places)
        buckets: dict[str, list[Place]] = {"liked": [], "fine": [], "disliked": []}
        for position, place in enumerate(chosen):
            buckets[bucket_for(person, place, position, len(chosen))].append(place)

        visited_by[person.username] = {}
        scores_by[person.username] = {}

        for bucket, members in buckets.items():
            for rank, place in enumerate(members):
                score = score_for(bucket, rank, len(members))
                visited_by[person.username][place.slug] = bucket
                scores_by[person.username][place.slug] = score

                pool = (
                    NOTES_GOOD
                    if bucket == "liked"
                    else NOTES_MIXED
                    if bucket == "fine"
                    else NOTES_POOR
                )
                has_note = stable_int(person.username, place.slug, "note") % 10 < 6
                note = pick(pool, person.username, place.slug) if has_note else None

                days_ago = 5 + stable_int(person.username, place.slug, "when") % 900
                paid = place.price_tier > 0
                amount = place.price_usd if paid and place.price_usd else None
                value = (
                    1 + stable_int(person.username, place.slug, "value") % 5
                    if paid
                    else None
                )
                crowd = 1 + stable_int(person.username, place.slug, "crowd") % 5
                minutes = 20 + stable_int(person.username, place.slug, "mins") % 8 * 20
                companion = ["solo", "partner", "friends", "family", "group_tour"][
                    stable_int(person.username, place.slug, "who") % 5
                ]

                rows.append(
                    f"  ('{person.uid}',"
                    f" (select id from public.places"
                    f" where slug = {sql_text(place.slug)}),"
                    f" '{bucket}', {rank}, {score}, {sql_text(note)},"
                    f" current_date - {days_ago},"
                    f" {'true' if paid else 'false'},"
                    f" {amount if amount else 'null'},"
                    f" {value if value else 'null'},"
                    f" {crowd}, {minutes}, '{companion}',"
                    f" {'true' if bucket != 'disliked' else 'false'},"
                    f" now() - interval '{days_ago} days')"
                )
    add(",\n".join(rows) + ";")
    add("")

    add("insert into public.want_to_go (user_id, place_id, source, created_at)")
    rows = []
    for person in people:
        candidates = [
            place
            for place in places
            if place.slug not in visited_by[person.username]
            and place.category in person.categories
        ]
        wanted = candidates[: 3 + stable_int(person.username, "want") % 8]
        for offset, place in enumerate(wanted):
            rows.append(
                f"  select '{person.uid}'::uuid,"
                f" (select id from public.places"
                f" where slug = {sql_text(place.slug)}),"
                f" 'manual', now() - interval '{10 + offset} days'"
            )
    add("\nunion all\n".join(rows))
    add("on conflict do nothing;")
    add("")

    add("-- A realistic graph: popular accounts gain many followers, everyone has")
    add("-- a small cluster, and private accounts collect pending requests.")
    usernames = [person.username for person in people]
    by_username = {person.username: person for person in people}
    edges: set[tuple[str, str]] = set()
    for person in people:
        degree = 6 + stable_int(person.username, "degree") % 18
        for step in range(degree):
            target = usernames[
                stable_int(person.username, "follow", str(step)) % len(usernames)
            ]
            if target != person.username:
                edges.add((person.username, target))

    add("insert into public.follows")
    add("  (follower_id, followee_id, status, created_at) values")
    rows = []
    for follower, followee in sorted(edges):
        status = "pending" if by_username[followee].private else "accepted"
        rows.append(
            f"  ('{by_username[follower].uid}', '{by_username[followee].uid}',"
            f" '{status}', now() - interval '120 days')"
        )
    add(",\n".join(rows))
    add("on conflict do nothing;")
    add("")

    add("insert into public.post_likes (post_id, user_id, created_at)")
    add("select post.id, liker.id, post.created_at + interval '3 hours'")
    add("from public.posts as post")
    add("join public.profiles as liker on liker.id <> post.user_id")
    add("where ('x' || substr(md5(post.id::text || liker.username), 1, 8))")
    add("      ::bit(32)::bigint % 26 = 0")
    add("on conflict do nothing;")
    add("")

    comment_values = ",\n".join(f"    ({sql_text(text)})" for text in COMMENTS)
    add("insert into public.comments (post_id, user_id, body, created_at)")
    add("select post.id, author.id, phrase.body,")
    add("       post.created_at + interval '7 hours'")
    add("from public.posts as post")
    add("join public.profiles as author on author.id <> post.user_id")
    add("cross join lateral (")
    add("  select body from (values")
    add(comment_values)
    add("  ) as options(body)")
    add("  offset (('x' || substr(md5(post.id::text || author.username), 9, 8))")
    add(f"          ::bit(32)::bigint % {len(COMMENTS)})")
    add("  limit 1")
    add(") as phrase")
    add("where ('x' || substr(md5(post.id::text || author.username), 17, 8))")
    add("      ::bit(32)::bigint % 55 = 0;")
    add("")

    add("-- Pre-computed with the Part 8.2 formula, so every account has a")
    add("-- reasoned recommendation set without calling the Edge Function.")
    totals: dict[str, list[float]] = {}
    for person in people:
        for slug, score in scores_by[person.username].items():
            totals.setdefault(slug, []).append(score)
    community = {
        slug: (len(values), sum(values) / len(values))
        for slug, values in totals.items()
    }

    follow_map: dict[str, list[str]] = {}
    for follower, followee in edges:
        if not by_username[followee].private:
            follow_map.setdefault(follower, []).append(followee)

    rows = []
    for person in people:
        friend_scores: dict[str, list[tuple[str, float]]] = {}
        for friend in follow_map.get(person.username, []):
            for slug, score in scores_by[friend].items():
                friend_scores.setdefault(slug, []).append(
                    (by_username[friend].display_name, score)
                )

        for rank, (place, score, reason) in enumerate(
            recommend_for(
                person,
                places,
                visited_by[person.username],
                scores_by[person.username],
                friend_scores,
                community,
                place_by_slug,
            )
        ):
            rows.append(
                f"  ('{person.uid}',"
                f" (select id from public.places"
                f" where slug = {sql_text(place.slug)}),"
                f" {rank}, {round(score, 4)}, {sql_text(reason)}, now())"
            )

    add("insert into public.recommendations")
    add("  (user_id, place_id, rank, score, reason, generated_at) values")
    add(",\n".join(rows))
    add("on conflict (user_id, place_id) do update set")
    add("  rank = excluded.rank, score = excluded.score,")
    add("  reason = excluded.reason;")
    add("")

    add("-- Score-derived badges need final scores, so evaluate last.")
    add("select public.evaluate_badges_for_user(id) from public.profiles;")
    add("")
    add("commit;")
    return "\n".join(out) + "\n"


__all__ = ["emit", "recommend_for", "math"]
